### ISSUE TITLE
Bug in datetime tests

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#472]
@zerok discovered some date-time bugs in zerok/pyvideosearch#2
Those are fixed in #471, but it should be discovered by the tests.
What are the valid date formats? 

Format | Spec | Example
--- | --- | ---
Full date-time | YYYY-MM-DD**T**hh:mm:ss+hh:mm | 2018-03-05T18:44:44+01:00
Date-time without timezone | YYYY-MM-DD**T**hh:mm:ss  | 2018-03-05T18:44:44
Date | YYYY-MM-DD | 2018-03-05

Date format is more than 90% of the video data in the repository
Full date-time is what is described in `data/.schemas/video.json`

Full date-time is useful to show event talks in chronological order, but takes more effort to look for the time zone and the DST (Daylight Saving Time) of the day (we have at least one event with a DST change in the middle). 
Date-time without timezone is less work but not so standard (?)

What date formats we want to support?
Should `data/.schemas/video.json` catch malformed dates? Like: `"recorded": "2013-5-10",`

**Comment by zerok** [comment]
@Daniel-at-github So far PyVideoSearch only supports the date section of RFC3339. That being said, personally I'd suggest sticking with RFC3339 datetimes for pyvideo simply because they are the easiest to work with and should therefore also be enforced by the testsuite.

If that's OK with you, I'd extend pyvideosearch over the next couple of days to support full RFC3339 datetimes include timezones.

For pyvideo itself, perhaps someone of could take a look at [pendulum](https://pendulum.eustace.io/) or another datetime library for Python which handles timezones more gracefully than the datetime module in the stdlib :)

**Comment by zerok** [comment]
I've updated pyvideosearch to support RFC3339 as well as the following two sub-formats:

* `2006-01-02T15:04:05`
* `2006-01-02`

These changes are live now.
